aesop_web/aesop/urls.py
from django.urls import path
from . import views

app_name = 'aesop'

urlpatterns = [
    path('', views.index, name='index'),
    path('page1/<int:story_id>', views.page1, name='page1'),
    # path('page2/<int:story_id>', views.page2, name='page2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('recode', views.recode, name='recode'),
    path('creat_text', views.creat_text, name='creat_text'),
    path('creat_image', views.creat_image, name='creat_image'),
    path('page2', views.page2, name='page2'),
]

aesop_web/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

aesop_web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from aesop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aesop/', include('aesop.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # '/' 에 해당되는 path
    path('gen_story/', include('gen_story.urls')),
]

aesop_web/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- aesop CSS -->
    <link rel="stylesheet" type="text/css" href="{f% static'/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <!-- ---------for_creat_text_page------------- -->
    <link rel="stylesheet" href="/static/css/style.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- ---------for_creat_text_page------------- -->
    <title>Hello, Aesop!</title>
    {% block html_header %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand">
        <div class="container-fluid">

     <!-- 로고이미지 클릭시 홈버튼 이동 이동 -->
      <a href="{% url 'aesop:index' %}"><img src="/static/images/Aesop+_small_logo.jpg" class="brand-logo" alt=""></a>
            <ul class="nav-links">
                <!-- 왼쪽 상단 메뉴바 -->
                <li class="nav-items"><a href="{% url 'aesop:recode' %}">녹음하기</a></li>
                <li class="nav-items"><a href="{% url 'aesop:creat_text' %}">동화 만들기</a></li>
                <li class="nav-items"><a href="{% url 'aesop:creat_image' %}">그림 그려보기</a></li>
                
              </ul>

            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="right-container"> 

                    <!-- 오른쪽 상단 검색상자 -->
                    <input type="text" class="search-box" placeholder="검색">
        
                </div>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS 이거 없으면 로그인 없어짐 ..↓ -->
<script src="{% static 'bootstrap.min.js' %}"></script>



{% block html_body %}
{% endblock %}
</body>
</html>

aesop_web/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}