aesop_web/aesop/urls.py
from django.urls import path
from . import views

app_name = 'aesop'

urlpatterns = [
    path('', views.index, name='index'),
    path('page1/<int:story_id>', views.page1, name='page1'),
    # path('page2/<int:story_id>', views.page2, name='page2'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('recode', views.recode, name='recode'),
    path('creat_text', views.creat_text, name='creat_text'),
    path('creat_image', views.creat_image, name='creat_image'),
    path('page2', views.page2, name='page2'),
]

aesop_web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from aesop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aesop/', include('aesop.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # '/' 에 해당되는 path
    path('gen_story/', include('gen_story.urls')),
]

aesop_web/aesop/models.py
from cgitb import text
from turtle import title
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class Story(models.Model):
    # id = models.PositiveIntegerField(primary_key=True)
    title = models.TextField()
    text = models.TextField()
    image = models.TextField()

aesop_web/aesop/forms.py
from django import forms
from aesop.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

aesop_web/aesop/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm, AnswerForm
from .models import Question, Story



# def index(request):
#     return render(request, 'base.html')

def index(request):
    story_all = Story.objects.all()
    story = {'story_all':story_all}
    # for i in story_kr:
    #     print("제목 : ",i)
    return render(request, 'aesop/main.html', story)    

def page1(request, story_id):
    context = {}
    story = get_object_or_404(Story, id=story_id)
    context['story'] = story
    return render(request, 'aesop/page1.html', context)

def page2(request):
    return render(request, 'aesop/page2.html')

# def page2(request, story_id):
#     context = {}
#     story = get_object_or_404(Story, id=story_id)
#     context['story'] = story
#     return render(request, 'aesop/page2.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'aesop/question_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('aesop:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'aesop/question_detail.html', context)


def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('aesop:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'aesop/question_form.html', context)

def main_1(request):
    return render(request,'aesop/main.html') 

def recode(request):
    return render(request, 'aesop/recode.html')

def creat_text(request):
    return render(request, 'aesop/creat_text.html')

def creat_image(request):
    return render(request, 'aesop/creat_image.html')

aesop_web/templates/aesop/creat_image.html
{% extends "base.html" %}
{% load static %}
{% block html_header %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
{% endblock %}
{% block html_body %}

<image_meta>
    <div class="image_text">
        <div class="image_home-story-text-block">
            <div class="image_home-story-text-content">     
                <!--       제목 -->
				<div class="image_image-box">
					<img src="http://brunobrito.pt/image.jpg" alt="Roman looked Strong">
				  </div>
            </div>
        </div>
</meta>
<!-- -------------------입력 상자----------------- -->
<!DOCTYPE html>
<image_html1>
<image_head1>
	<title> Secret Message </title>
	<script type="text/javascript">
function getSecretMessage(message){
this.message = (message.split(' ')).join('');
      this.size = this.message.length;
      this.normalizeText_Rect=[],
      this.normalizeText_Chunk ="";
      this.encodedText_Rect=[];
      this.encodedText_Chunk="";
      this.col=0;
      this.rows=0;
	}
	getSecretMessage.prototype.getCol=function(){
		let col = 0;
		for(let i=1; i<this.size; i++){
	     if(i*i == this.size){col=i; break}
	     else if(i*i >= this.size){col=i; break}
}

	return col;

	}
	getSecretMessage.prototype.Encode=function(){
		//get col
		this.col = this.getCol();

		//get normalise chunk
		for (var j = 0; j<this.size; j++) {
		this.normalizeText_Chunk += this.message.charAt(j);
		if ((j+1) % this.col === 0 &&
			j !== this.size-1) this.normalizeText_Chunk +=' ';
	}


	//get normalise Rect
	this.normalizeText_Rect = this.normalizeText_Chunk.split(' ');

	//check for nth character short and pad
let last =this.normalizeText_Rect[this.normalizeText_Rect.length-1]

	if(last.length<this.col){	this.normalizeText_Rect[this.normalizeText_Rect.length-1] =last.padEnd(last.length+1)
	}
	//get rows
	this.rows =  this.normalizeText_Rect.length

	//now encode message
	for (let z=0; z<this.col; z++){
		    var enc= "";
		    for(let k=0; k<this.rows; k++){
		    	    enc+=this.normalizeText_Rect[k].charAt(z)
		    }
		    //get encode rect
		   this.encodedText_Rect.push(enc)
	}


this.encodedText_Chunk =this.encodedText_Rect.join(" ");

	}

	getSecretMessage.prototype.display=function(){

		this.Encode()


var div1= document.getElementsByClassName('out')[0],
div2= document.getElementsByClassName('out')[1],
div3= document.getElementsByClassName('out')[2],
div4= document.getElementsByClassName('out')[3];



      div1.innerHTML=this.normalizeText_Chunk
		div2.innerHTML=this.normalizeText_Rect.join('<br/>')
		div3.innerHTML=this.encodedText_Chunk
	    div4.innerHTML=this.encodedText_Rect.join('<br/>')


	}


function handleIt(){
var sentence = document.forms["myForm"]["sentence"].value;
let test = new getSecretMessage(sentence);
 test.display()

}






    </script>
</image_head1>

<image_body1>

<div class="image_container">
<form method="post" action="javascript:handleIt()" name="myForm" onsubmit="return validateForm()">
<div>
    <br>
	<label class="image_nm">이미지 생성을 위한 문장을 작성해보세요!</label>
    <br>
    <br>
	<textarea rows="5" cols="100" type ="text" name="sentence" id="sentence"> </textarea>
</div>
<br />
<input  class="image_btn btn-primary btn-lg" name="Submit" type="button" value="실행" />
<input  class="image_btn btn-primary btn-lg" name="save" type="submit" value="저장" />
</form>
</div>



<script>

function validateForm(){
	 var sentence = document.forms["myForm"]["sentence"].value;

	 if(sentence == null||sentence == ""){
		alert("저장되었습니다");
		return false;
	 }

	 if(sentence.length < 50){
	 	alert("최소 50자 이상이 되어야 합니다.");
	 		return false;
	 }
}
// var mess = "If man was meant to stay on the ground god would have given us roots";



</script>

</image_body1>
</image_html1>

{% endblock %}

aesop_web/templates/aesop/creat_text.html
{% extends "base.html" %}
{% load static %}
{% block html_header %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
{% endblock %}
{% block html_body %}

<creat_meta>
    <div class="creat_text">
        <div class="creat_home-story-text-block">
            <div class="creat_home-story-text-content">     
                <!--       제목 -->
        <h1>만들어진 동화를 읽어보세요!</h1>
            <br>
        <!--       본문 -->
            <p>옛날옛날, 어느 작은 연못에 엄마 청개구리와 아들 청개구리가 살고 있었습니다. 아들 청개구리는 엄마 청개구리의 말을 듣지 않고 무엇이든 거꾸로 해서 엄마의 마음을 아프게 하곤 했답니다.
            엄마 청개구리가 “숲 속에는 뱀이 많아 위험하니 가지 말아라” 하면 아들 청개구리는 일부러 숲에 놀러 갔다가 하마터면 뱀한테 잡아 먹힐 뻔 하기도 하고, 엄마 청개구리가 “개굴개굴- 하고 울어보렴” 하고 우는 법을 가르쳐 주면 아들 청개구리는 어김 없이 “굴개굴개, 굴게굴게” 하고 울기도 했죠. 말을 듣지 않는 아들 청개구리 때문에 엄마 청개구리는 매일 너무 마음이 아팠지만, 아들 청개구리는 어느 하루도 엄마 청개구리의 말을 듣는 날 없이 반대로만 행동하여 속을 썩였답니다.
            어느 날, 아들 청개구리만을 걱정하며 속상해 하던 엄마 청개구리는 결국 병이 나서 쓰러져 버렸습니다. 죽음이 다가온 것을 알게 된 엄마 청개구리는 아들 청개구리에게 말했습니다.            
            </p>
            </div>
        </div>
</creat_meta>
<!-- -------------------입력 상자----------------- -->
<!DOCTYPE html>
<creat_html1>
<creat_head1>
	<title> Secret Message </title>
	<!-- <script type="text/javascript">
function getSecretMessage(message){
this.message = (message.split(' ')).join('');
      this.size = this.message.length;
      this.normalizeText_Rect=[],
      this.normalizeText_Chunk ="";
      this.encodedText_Rect=[];
      this.encodedText_Chunk="";
      this.col=0;
      this.rows=0;
	}
	getSecretMessage.prototype.getCol=function(){
		let col = 0;
		for(let i=1; i<this.size; i++){
	     if(i*i == this.size){col=i; break}
	     else if(i*i >= this.size){col=i; break}
}

	return col;

	}
	getSecretMessage.prototype.Encode=function(){
		//get col
		this.col = this.getCol();

		//get normalise chunk
		for (var j = 0; j<this.size; j++) {
		this.normalizeText_Chunk += this.message.charAt(j);
		if ((j+1) % this.col === 0 &&
			j !== this.size-1) this.normalizeText_Chunk +=' ';
	}


	//get normalise Rect
	this.normalizeText_Rect = this.normalizeText_Chunk.split(' ');

	//check for nth character short and pad
let last =this.normalizeText_Rect[this.normalizeText_Rect.length-1]

	if(last.length<this.col){	this.normalizeText_Rect[this.normalizeText_Rect.length-1] =last.padEnd(last.length+1)
	}
	//get rows
	this.rows =  this.normalizeText_Rect.length

	//now encode message
	for (let z=0; z<this.col; z++){
		    var enc= "";
		    for(let k=0; k<this.rows; k++){
		    	    enc+=this.normalizeText_Rect[k].charAt(z)
		    }
		    //get encode rect
		   this.encodedText_Rect.push(enc)
	}


this.encodedText_Chunk =this.encodedText_Rect.join(" ");

	}

	getSecretMessage.prototype.display=function(){

		this.Encode()


var div1= document.getElementsByClassName('out')[0],
div2= document.getElementsByClassName('out')[1],
div3= document.getElementsByClassName('out')[2],
div4= document.getElementsByClassName('out')[3];



      div1.innerHTML=this.normalizeText_Chunk
		div2.innerHTML=this.normalizeText_Rect.join('<br/>')
		div3.innerHTML=this.encodedText_Chunk
	    div4.innerHTML=this.encodedText_Rect.join('<br/>')


	}


function handleIt(){
var sentence = document.forms["myForm"]["sentence"].value;
let test = new getSecretMessage(sentence);
 test.display()

}






    </script> -->
</creat_head1>

<creat_body1>

<div class="creat_container">
<form method="post" action="javascript:handleIt()" name="myForm" onsubmit="return validateForm()">
<div>
    <br>
	<label class="nm">동화 생성을 위한 문장을 작성해주세요!</label>
    <br>
    <br>
	<textarea rows="5" cols="100" type ="text" name="sentence" id="sentence"> </textarea>
</div>
<br />
<input  class="creat_btn btn-primary btn-lg" name="Submit" type="button" value="실행" />
<input  class="creat_btn btn-primary btn-lg" name="save" type="submit" value="저장" />
</form>
</div>



<script>

function validateForm(){
	 var sentence = document.forms["myForm"]["sentence"].value;

	 if(sentence == null||sentence == ""){
		alert("저장되었습니다");
		return false;
	 }

	 if(sentence.length < 50){
	 	alert("최소 50자 이상이 되어야 합니다.");
	 		return false;
	 }
}
// var mess = "If man was meant to stay on the ground god would have given us roots";



</script>

</creat_body1>
</creat_html1>

{% endblock %}

aesop_web/templates/aesop/main.html
{% extends "base.html" %}
{% load static %}
{% block html_header %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
{% endblock %}
{% block html_body %}

    <!-- 슬라이더 -->
    <div class="carousel-container">
      <div class="carousel">
      </div>
    </div>

  

    <h1 class="title">추천 동화</h1>
    <div class="movies-list">
      <!-- 양옆 화살표 버튼 -->
        <button class="pre-btn"><img src="/static/images/pre.png" alt=""></button>
        <button class="nxt-btn"><img src="/static/images/nxt.png" alt=""></button>
        <div class="card-container">
          {% for story in story_all %}
            {% if story.id >= 97 and story.id < 105 %} <a href="page1/{{story.id}}">
            <div class="card">
              <img src="{{story.image}}" class="card-img" alt="">
              <div class="card-body">
                <h2 class="name">{{story.title}}</h2>
              </div>
            </div>
             </a>
            {% endif %}
          {% endfor %}
        </div>

        <h1 class="title">한국 동화</h1>
            <div class="movies-list">
              <!-- 양옆 화살표 버튼 -->
                <button class="pre-btn"><img src="/static/images/pre.png" alt=""></button>
                <button class="nxt-btn"><img src="/static/images/nxt.png" alt=""></button>
                <div class="card-container">
                  {% for story in story_all %}
                    {% if story.id >= 0 and story.id < 9 %} <a href="page1/{{story.id}}">
                    <div class="card">
                      <img src="{{story.image}}" class="card-img" alt="">
                      <div class="card-body">
                        <h2 class="name">{{story.title}}</h2>
                      </div>
                    </div>
                     </a>
                    {% endif %}
                  {% endfor %}
                </div>


        <h1 class="title">외국 동화</h1>
        <div class="movies-list">
          <!-- 양옆 화살표 버튼 -->
          <button class="pre-btn"><img src="/static/images/pre.png" alt=""></button>
          <button class="nxt-btn"><img src="/static/images/nxt.png" alt=""></button>
          <div class="card-container">
            {% for story in story_all %}
              {% if story.id >= 110 and story.id < 118 %} <a href="page1/{{story.id}}">
              <div class="card">
                <img src="{{story.image}}" class="card-img" alt="">
                <div class="card-body">
                  <h2 class="name">{{story.title}}</h2>
                </div>
              </div>
               </a>
              {% endif %}
            {% endfor %}
          </div>
              
            


    <script src="/static/data.js" ></script>
    <script src="/static/app.js" ></script>

    {% endblock %}

aesop_web/templates/aesop/page1.html
{% extends "base.html" %}
{% load static %}
{% block html_header %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
{% endblock %}
{% block html_body %}

      <section class="info" >
        <br><br><br><br><br><br><br>
        <!-- <h2>동화 선택</h2> -->

      <div class="title" style="text-align:center" > 
        <img src="{{story.image}}" alt="My Image" >
        <br><br>
        <form name="voice_choice" action="index.html" method= "get" >
          <select name="voice" class="btn-lg" style=" background:rgb(87, 118, 145); color: white">
            <option value="">-- 목소리 선택 --</option>
            <option value="남(전래동화)">엄마</option>
            <option value="여(전래동화)">할아버지</option>
          </select>            
          <!-- <a href="{% url 'aesop:index' %}"></a> -->
          <button type="button" class="run_btn btn-outline-secondary">
            <a href="aiaesop\templates\aesop\page2.html">재생</a></button>
        
        </section>
        </form>
      </div>




  {% endblock %}

aesop_web/templates/aesop/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'aesop:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

aesop_web/templates/aesop/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

aesop_web/templates/aesop/recode.html
{% extends "base.html" %}
{% load static %}
{% block html_header %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
{% endblock %}
{% block html_body %}

<meta>
    <div class="recode_text">
        <div class="recode_home-story-text-block">
            <div class="recode_home-story-text-content">     
                <!--       제목 -->
        <h1>녹음 텍스트</h1>
        <h3>(글자를 따라서 읽어 주세요)</h3>
            <br>
        <!--       본문 -->
            <p href="#">옛날옛날, 어느 작은 연못에 엄마 청개구리와 아들 청개구리가 살고 있었습니다. 아들 청개구리는 엄마 청개구리의 말을 듣지 않고 무엇이든 거꾸로 해서 엄마의 마음을 아프게 하곤 했답니다.
            엄마 청개구리가 “숲 속에는 뱀이 많아 위험하니 가지 말아라” 하면 아들 청개구리는 일부러 숲에 놀러 갔다가 하마터면 뱀한테 잡아 먹힐 뻔 하기도 하고, 엄마 청개구리가 “개굴개굴- 하고 울어보렴” 하고 우는 법을 가르쳐 주면 아들 청개구리는 어김 없이 “굴개굴개, 굴게굴게” 하고 울기도 했죠. 말을 듣지 않는 아들 청개구리 때문에 엄마 청개구리는 매일 너무 마음이 아팠지만, 아들 청개구리는 어느 하루도 엄마 청개구리의 말을 듣는 날 없이 반대로만 행동하여 속을 썩였답니다.
               
            </p>
            </div>
        </div>
    </div class="recode_text">
    <div class="recode-btn">
        <button type="button" class="btn btn-success btn-lg" href="#">  재생  </button>
        <button type="button" class="btn btn-danger btn-lg" href="#">  녹음  </button>
        <button type="button" class="btn btn-secondary btn-lg" href="#">  저장  </button>
        <button type="button" class="btn btn-light btn-lg" href="#">  다시하기  </button>
        <button type="button" class="btn btn-warning btn-lg" href="#">  다음  </button>


    </div>
</meta>

{% endblock %}